### ISSUE TITLE
Wrong dependency version of `DimensionalData` package

### ISSUE THREAD

**Issue by ferdiu** [brendanjohnharris/Catch22.jl#20]
The code since `v0.2.2` is importing `DimensionalData.Dimensions` which is available since `DimensionalData` version `v0.19.*` but the package has `v0.18` in its `compat` section.

## Result

The package will not precompile when used in a different environment.

## Proposed change

```
DimensionalData = "≥ 0.18"
```

to

```
DimensionalData = "≥ 0.19"
```

in `Porject.toml`.

**Comment by brendanjohnharris** [comment]
Nice, fixed :)
