### ISSUE TITLE
multi threading use question

### ISSUE THREAD

**Issue by xgdgsc** [brendanjohnharris/Catch22.jl#31]
When I try to use it in multi threads with rolling window like::
```julia
cres = zeros(size(X)[1], length(meths))
 Threads.@threads for j in eachindex(meths)
        for i in 1:size(X, 1)-window
            @inbounds cres[i+window, j] = catch22[meths[j]](X[i:i+window])
        end
    end
```
or 
```julia
cres = zeros(size(X)[1], length(meths))
for j in eachindex(meths)
         Threads.@threads for i in 1:size(X, 1)-window
            @inbounds cres[i+window, j] = catch22[meths[j]](X[i:i+window])
        end
    end
```
meths is a vector of method symbol names.
The cpu usage seems never come close to what I allowed(42 threads). It usually takes only less than 10 threads in the first example and only 1 thread in the second example. Is it a limitation of ccall?

**Comment by brendanjohnharris** [comment]
Hi @xgdgsc, thansk for the question

I'm not certain what could be causing the restricted cpu usage, but a couple of thoughts:
- For the first example, calling @threads on the loop over `meths` wouldn't use all 42 threads, since there are only features in `meths` (unless you've defined some extras?)
- The second loop running with restricted threads is more of a problem. I've tried to replicate the issue below, with three different ways of running the calculation in parallel. The last option, `h()`, is preferred, since it will return an annotated `FeatureMatrix`. Could you try the third syntax and let me know if you still run into a restricted number of threads?

```julia
    X = randn(2500)
    meths = Catch22.featurenames
    cres = zeros(size(X)[1], length(meths))
    window=100
    f() = for j in eachindex(meths)
        Threads.@threads for i in 1:size(X, 1)-window
            @inbounds cres[i+window, j] = catch22[meths[j]](X[i:i+window])
        end
    end

    g() = Threads.@threads for i in 1:size(X, 1)-window
        @inbounds cres[i+window, :] = catch22[meths](X[i:i+window])
    end

    h() = catch22[meths](hcat([X[i:i+window] for i in 1:size(X, 1)-window]...))

```

```julia
julia> using BenchmarkTools
julia> BenchmarkTools.DEFAULT_PARAMETERS.seconds = 20
julia> f(); @benchmark f()
BenchmarkTools.Trial: 265 samples with 1 evaluation.
 Range (min … max):  184.829 ms … 507.346 ms  ┊ GC (min … max):  0.00% … 61.19%
 Time  (median):     194.295 ms               ┊ GC (median):     0.00%
 Time  (mean ± σ):   226.884 ms ±  85.059 ms  ┊ GC (mean ± σ):  14.49% ± 19.04%

  ▆█▇▅                                                           
  █████▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▄▁▁▄▄▄▄▆█▅▇▄▆▅▅▆ ▅
  185 ms        Histogram: log(frequency) by time        470 ms <

 Memory estimate: 68.38 MiB, allocs estimate: 474181.

julia> g(); @benchmark g()
BenchmarkTools.Trial: 307 samples with 1 evaluation.
 Range (min … max):  156.095 ms … 462.991 ms  ┊ GC (min … max):  0.00% … 64.72%
 Time  (median):     166.929 ms               ┊ GC (median):     0.00%
 Time  (mean ± σ):   195.428 ms ±  82.513 ms  ┊ GC (mean ± σ):  14.89% ± 19.28%

  ▂▇█▃                                                           
  ████▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇▆▁▅█▅▇▅▅▇ ▆
  156 ms        Histogram: log(frequency) by time        449 ms <

 Memory estimate: 58.77 MiB, allocs estimate: 506812.

julia> h(); @benchmark h()
BenchmarkTools.Trial: 336 samples with 1 evaluation.
 Range (min … max):  152.604 ms … 427.631 ms  ┊ GC (min … max): 0.00% … 60.86%
 Time  (median):     162.475 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   178.969 ms ±  48.173 ms  ┊ GC (mean ± σ):  9.43% ± 14.86%

  ▁▆█▇▅▁                                                         
  ██████▆▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▄▇▅▇▆▅▅▁▄▄▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▄▁▆▆▆▇▅▄▅ ▆
  153 ms        Histogram: log(frequency) by time        352 ms <

 Memory estimate: 49.07 MiB, allocs estimate: 303107.
 ```

**Comment by brendanjohnharris** [comment]
I haven't run calculations for long enough to check if CPU usage wasn't maximised, but when I get home today I'll add some tests for this and a method for multithreading over collections of time series. Thanks for bringing this up!

**Comment by brendanjohnharris** [comment]
Sorry for the delay, I just got around to adding a method for vectors of vectors. If I use that approach, I get the following full cpu usage:
![2023-05-06_15-47](https://user-images.githubusercontent.com/42064608/236602971-accc1ad4-7176-46f0-ae42-d677724641a4.png)

If I try the approach from earlier, manually constructing a threaded loop, I get:
![2023-05-06_15-51](https://user-images.githubusercontent.com/42064608/236603116-5cdc2006-c3d1-4e36-9f01-eb4580616f46.png)

**Comment by xgdgsc** [comment]
Thanks. I tried the latest update and it works!
