### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by xgdgsc** [brendanjohnharris/Catch22.jl#32]
I did a `@profview  catch22[meths](@views [X[i:i+window-1] for i in 1:size(X, 1)-window] ) C = true` and saw a large portion of `dlopen` and `dlsym` . Is this avoidable ? I searched in FFTW.jl and didn' t find them.

**Comment by brendanjohnharris** [comment]
Hmm I'm not sure if those calls can be removed entirely: `dlopen` and `dlsym` are functions related to opening a C library and retrieving a symbol from it: you can find them in the `Libdl` module.

I have tried a few ways of opening a C library and caching functions, but you have to be very careful in avoiding segfaults.
It seems there should be a way using macro's, but I haven't found one so far...

**Comment by brendanjohnharris** [comment]
Ah I think I've fixed this! All it took was declaring the C function pointers as `global`s. I've pushed that to main, if you've got some time spare could you check if you still see `dlopen` and `dlsym` in the profileview of `catch22()`?

**Comment by xgdgsc** [comment]
Thanks. Yes. They disappear from profview results.

**Comment by brendanjohnharris** [comment]
Awesome! Thanks for spotting all of these issues, I never would have noticed 😅
